[project]
name = "zotero-search-preview"
version = "0.1.0"
description = "Search and preview Zotero items using a web interface"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pymupdf>=1.25.4",
    "uvicorn>=0.34.0",
]
